# Generated by Django 2.2.7 on 2019-11-23 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('field0', models.CharField(default='1', max_length=30)),
                ('field1', models.CharField(default='2', max_length=30)),
                ('field2', models.CharField(default='3', max_length=30)),
                ('field3', models.CharField(default='4', max_length=30)),
                ('field4', models.CharField(default='5', max_length=30)),
                ('field5', models.CharField(default='6', max_length=30)),
                ('field6', models.CharField(default='7', max_length=30)),
                ('field7', models.CharField(default='8', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReelSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reel0', models.OneToOneField(default='reel1', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.Reel')),
                ('reel1', models.OneToOneField(default='reel2', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.Reel')),
                ('reel2', models.OneToOneField(default='reel3', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.Reel')),
                ('reel3', models.OneToOneField(default='reel4', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.Reel')),
                ('reel4', models.OneToOneField(default='reel5', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.Reel')),
                ('reel5', models.OneToOneField(default='reel6', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.Reel')),
                ('reel6', models.OneToOneField(default='reel7', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.Reel')),
                ('reel7', models.OneToOneField(default='reel8', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main_app.Reel')),
            ],
            options={
                'ordering': ['owner'],
            },
        ),
    ]
