# Generated by Django 2.2.7 on 2019-11-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('name', models.CharField(max_length=32)),
                ('slot0', models.TextField()),
                ('slot1', models.TextField()),
                ('slot2', models.TextField()),
                ('slot3', models.TextField()),
                ('slot4', models.TextField()),
                ('slot5', models.TextField()),
                ('slot6', models.TextField()),
                ('slot7', models.TextField()),
            ],
        ),
    ]
