# Generated by Django 2.2.7 on 2019-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reelset',
            name='reel0',
        ),
        migrations.RemoveField(
            model_name='reelset',
            name='reel1',
        ),
        migrations.RemoveField(
            model_name='reelset',
            name='reel2',
        ),
        migrations.RemoveField(
            model_name='reelset',
            name='reel3',
        ),
        migrations.RemoveField(
            model_name='reelset',
            name='reel4',
        ),
        migrations.RemoveField(
            model_name='reelset',
            name='reel5',
        ),
        migrations.RemoveField(
            model_name='reelset',
            name='reel6',
        ),
        migrations.RemoveField(
            model_name='reelset',
            name='reel7',
        ),
        migrations.AddField(
            model_name='reelset',
            name='reels',
            field=models.ManyToManyField(to='main_app.Reel', verbose_name='list of reels'),
        ),
    ]
