# Generated by Django 2.2.7 on 2019-11-23 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultreelset',
            name='reels',
        ),
        migrations.RemoveField(
            model_name='reelset',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='reelset',
            name='reels',
        ),
        migrations.DeleteModel(
            name='DefaultReel',
        ),
        migrations.DeleteModel(
            name='DefaultReelSet',
        ),
        migrations.DeleteModel(
            name='Reel',
        ),
        migrations.DeleteModel(
            name='ReelSet',
        ),
    ]
