# Generated by Django 2.2.7 on 2019-11-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191130_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reelset',
            name='reels',
        ),
        migrations.AddField(
            model_name='reel',
            name='reelset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='main_app.ReelSet'),
            preserve_default=False,
        ),
    ]
