# Generated by Django 2.2.7 on 2019-11-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191130_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultreel',
            name='field0',
            field=models.CharField(default='1', max_length=60),
        ),
        migrations.AlterField(
            model_name='defaultreel',
            name='field1',
            field=models.CharField(default='2', max_length=60),
        ),
        migrations.AlterField(
            model_name='defaultreel',
            name='field2',
            field=models.CharField(default='3', max_length=60),
        ),
        migrations.AlterField(
            model_name='defaultreel',
            name='field3',
            field=models.CharField(default='4', max_length=60),
        ),
        migrations.AlterField(
            model_name='defaultreel',
            name='field4',
            field=models.CharField(default='5', max_length=60),
        ),
        migrations.AlterField(
            model_name='defaultreel',
            name='field5',
            field=models.CharField(default='6', max_length=60),
        ),
        migrations.AlterField(
            model_name='defaultreel',
            name='field6',
            field=models.CharField(default='7', max_length=60),
        ),
        migrations.AlterField(
            model_name='defaultreel',
            name='field7',
            field=models.CharField(default='8', max_length=60),
        ),
        migrations.AlterField(
            model_name='reel',
            name='field0',
            field=models.CharField(default='1', max_length=60),
        ),
        migrations.AlterField(
            model_name='reel',
            name='field1',
            field=models.CharField(default='2', max_length=60),
        ),
        migrations.AlterField(
            model_name='reel',
            name='field2',
            field=models.CharField(default='3', max_length=60),
        ),
        migrations.AlterField(
            model_name='reel',
            name='field3',
            field=models.CharField(default='4', max_length=60),
        ),
        migrations.AlterField(
            model_name='reel',
            name='field4',
            field=models.CharField(default='5', max_length=60),
        ),
        migrations.AlterField(
            model_name='reel',
            name='field5',
            field=models.CharField(default='6', max_length=60),
        ),
        migrations.AlterField(
            model_name='reel',
            name='field6',
            field=models.CharField(default='7', max_length=60),
        ),
        migrations.AlterField(
            model_name='reel',
            name='field7',
            field=models.CharField(default='8', max_length=60),
        ),
    ]
