# Generated by Django 2.2.7 on 2019-11-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191116_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotset',
            name='id',
        ),
        migrations.AlterField(
            model_name='slotset',
            name='owner',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
