# Generated by Django 2.2.7 on 2019-11-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191130_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultreelset',
            name='reels',
        ),
        migrations.AddField(
            model_name='defaultreel',
            name='reelset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reels', to='main_app.DefaultReelSet'),
            preserve_default=False,
        ),
    ]
