# Generated by Django 2.2.7 on 2019-12-07 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_auto_20191130_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultreel',
            name='field0',
        ),
        migrations.RemoveField(
            model_name='defaultreel',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='defaultreel',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='defaultreel',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='defaultreel',
            name='field4',
        ),
        migrations.RemoveField(
            model_name='defaultreel',
            name='field5',
        ),
        migrations.RemoveField(
            model_name='defaultreel',
            name='field6',
        ),
        migrations.RemoveField(
            model_name='defaultreel',
            name='field7',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='field0',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='field1',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='field2',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='field3',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='field4',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='field5',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='field6',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='field7',
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('content', models.CharField(max_length=60)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='main_app.Reel')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('content', models.CharField(max_length=60)),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='main_app.DefaultReel')),
            ],
        ),
    ]
