# Generated by Django 2.2.7 on 2019-12-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191207_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultreel',
            name='leave_empty',
            field=models.BooleanField(default=False),
        ),
    ]
